export declare enum RecorderState {
    INITIAL = "INITIAL",
    RECORDING = "RECORDING",
    STOPPED = "STOPPED",
    FINISHING = "FINISHING",
    SUCCESS = "SUCCESS",
    EXITED_ABNORMALLY = "EXITED_ABNORMALLY",
    ERROR = "ERROR"
}
