export enum RecorderState {
    INITIAL = 'INITIAL',
    RECORDING = 'RECORDING',
    PAUSED = 'PAUSED',
    STOPPING = 'STOPPING',
    CREATINGOUTFILE = 'CREATINGOUTFILE',
    CLEANING = 'CLEANING',
    COMPLETED = 'COMPLETED',
    PROCESS_EXITED_ABNORMALLY = 'PROCESS_EXITED_ABNORMALLY',
    ERROR = 'ERROR',
    WAITING_IN_QUEUE = 'WAITING_IN_QUEUE',
}
